name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tranlequocthong313/blog-post-workflow@main
        with:
          feed_list: 'https://viblo.asia/rss/authors/tranlequocthong313.rss'
